### PR TITLE
Added Readme and pip requirements to server/model/compute

### PR DESCRIPTION
**Pull request by andrewawang**
Added README.md and requirements.txt for Python libraries necessary for server/model/compute

### CODE REVIEW

**Comment by fyu** [comment]
- When people see this page. They have already installed python and pip. 
- Don't use header font for the list
- inline code only needs single quote

**Comment by andrewawang** [comment]
Fixed Readme. Style updated, fixed pointer to go setup readme.

**Comment by fyu** [comment]
How is this related to https://github.com/ucbdrive/scalabel/blob/master/server/README.md? Shall we merge this to that document?

**Comment by andrewawang** [comment]
It's part of the setup for the server, mostly for local backend. I'll merge the two documents and remove this readme from compute.

**Pull request merged**
