### PR TITLE
Convert create 

### PR DESCRIPTION
**Pull request by noahjimenez5844**
Converted create page to react/material-ui.

### CODE REVIEW

**Comment by noahjimenez5844** [comment]
Still has bug with uploading items

**Comment by xanderchf** [comment]
This pr looks nice! However, when I click the task link in the dashboard after creating a project, the link turns out to be invalid:
Screen Shot 2019-07-08 at 11 24 19 PM

**Comment by noahjimenez5844** [comment]
> This pr looks nice! However, when I click the task link in the dashboard after creating a project, the link turns out to be invalid:
> Screen Shot 2019-07-08 at 11 24 19 PM

I broke this renaming some ids, this should be fixed now

**Comment by noahjimenez5844** [comment]
How the page looks: 

image

**Pull request merged**
